[workspace]
members = [".", "entity", "migration"]

[package]
name = "oura-postgres-sink"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
anyhow = "1.0.53"
serde = "1.0.136"
tokio = { version = "1.16.1", features = ["full"] }
entity = { path = "entity" }
migration = { path = "migration" }
oura = { git = "https://github.com/txpipe/oura", branch = "main" }
pallas = "0.5.0-beta.0"
hex = "0.4.3"
tracing-subscriber = "0.3.9"
tracing = "0.1.31"
cardano-serialization-lib = "10.0.4"
dotenv = "0.15.0"
serde_json = "1.0.79"
base64 = "0.13.0"
bs58 = "0.4.0"
