[workspace]
members = [".", "entity", "migration"]

[package]
name = "oura-postgres-sink"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
serde = "1.0.136"
tokio = { version = "1.16.1", features = ["full"] }
entity = { path = "entity" }
migration = { path = "migration" }
oura = { git = "https://github.com/txpipe/oura", branch = "main" }
hex = "0.4.3"
