[GenesisBlockTask]

[GenesisTransactionTask]

[ByronBlockTask]
readonly=false

[ByronTransactionTask]
readonly=false

[ByronAddressTask]

[ByronOutputTask]

[ByronInputTask]

[MultieraBlockTask]
readonly=true

[MultieraTransactionTask]
readonly=true

[MultieraMetadataTask]
readonly=false

[MultieraAssetMintTask]
readonly=true

[MultieraCip25EntryTask]
